# INIQ GoReleaser configuration
# Documentation: https://goreleaser.com

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy

builds:
  - id: iniq
    main: ./cmd/iniq/main.go
    binary: iniq
    env:
      - CGO_ENABLED=0
    # Set version information via ldflags, matching current build process
    ldflags:
      - -s -w
      - -X github.com/teomyth/iniq/internal/version.version={{.Version}}
      - -X github.com/teomyth/iniq/internal/version.buildDate={{.Date}}
      - -X github.com/teomyth/iniq/internal/version.commit={{.Commit}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    # Ensure reproducible builds
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: iniq
    name_template: >-
      {{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    formats: [tar.gz]
    # Use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'SHA256SUMS.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: teomyth
    name: iniq
  name_template: "INIQ {{.Version}}"
  draft: false
  prerelease: auto
  extra_files:
    - glob: scripts/install.sh
  header: |
    # INIQ {{.Version}}
  footer: |
    ## Installation

    ### Option 1: Using the install script (Recommended)

    ```bash
    curl -L https://github.com/teomyth/iniq/releases/download/{{.Tag}}/install.sh | sudo bash
    ```

    ### Option 2: Manual installation

    #### Linux (AMD64)
    ```bash
    curl -L https://github.com/teomyth/iniq/releases/download/{{.Tag}}/iniq-linux-amd64.tar.gz -o iniq.tar.gz
    tar -xzf iniq.tar.gz
    chmod +x iniq
    sudo mv iniq /usr/local/bin/
    ```

    #### Linux (ARM64)
    ```bash
    curl -L https://github.com/teomyth/iniq/releases/download/{{.Tag}}/iniq-linux-arm64.tar.gz -o iniq.tar.gz
    tar -xzf iniq.tar.gz
    chmod +x iniq
    sudo mv iniq /usr/local/bin/
    ```

    ## Verify checksums

    ```bash
    curl -L https://github.com/teomyth/iniq/releases/download/{{.Tag}}/SHA256SUMS.txt -o SHA256SUMS.txt
    sha256sum -c SHA256SUMS.txt
    ```
